#!/usr/bin/env bash
# input:arg1 = domain arg2 = subdomain
# output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

if [ $# -eq 2 ]
then
	RECORD_TYPE=$(dig www.holberton.online | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
	DESTINATION=$(dig www.holberton.online | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
	echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
else
	var=$1
	declare -a subs=("www" "lb-01" "web-01" "web-02")
	for sub in ${subs[@]}; do
		RECORD_TYPE=$(dig ${sub}.${var} | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | sed '/./,$!d')
		DESTINATION=$(dig ${sub}.${var} | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | sed '/./,$!d')
		echo "The subdomain $sub is a $RECORD_TYPE record and points to $DESTINATION"
	done
fi
