#!/usr/bin/env bash
# set up web server
sudo apt-get update
sudo apt-get --yes install nginx

mkdir -p "/var/www/html"
echo "Holberton School for the win" > "/var/www/html/index.html"
service nginx reload
service nginx restart
