#!/usr/bin/env bash
# set up server 2
sudo apt-get -y update
sudo apt-get -y install nginx

mkdir -p /var/www/html
sudo service nginx start

echo "Holberton School" > /var/www/html/index.html
sudo sed -i "25i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart