#!/usr/bin/env bash
# This script is displaying "Holberton School " 10 times
i="0"

while [ $i -lt 10 ]
do
if (( i == 3)); then
	echo "bad luck"
elif (( i == 7)); then
	echo "good luck"
else
	echo "Holberton School"
fi
i=$((i+1))
done
